CREATE TABLE up_subscription(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
	LEVEL ENUM('Free', 'Standard', 'Premium') DEFAULT 'Free',
	PRICE INT NOT NULL DEFAULT 0,
	NUMBER_TREES INT NOT NULL DEFAULT 1
);

CREATE TABLE up_user(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    SUBSCRIPTION_ID INT NOT NULL DEFAULT 1,
    SUBSCRIPTION_BUY_TIME TIMESTAMP DEFAULT NULL,
    FOREIGN KEY (SUBSCRIPTION_ID) REFERENCES up_subscription(ID)
);

CREATE TABLE up_family_tree(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(100) NOT NULL,
    USER_ID INT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES up_user(ID)
);

CREATE TABLE up_person(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	SURNAME VARCHAR(50) NOT NULL,
	BIRTH_DATE DATE,
	DEATH_DATE DATE,
	GENDER ENUM('Male', 'Female'),
	TREE_ID INT NOT NULL,
	FOREIGN KEY (TREE_ID) REFERENCES up_family_tree(ID)
);

CREATE TABLE up_person_parent(
    PARENT_ID INT NOT NULL,
    CHILD_ID INT NOT NULL,
    FOREIGN KEY (PARENT_ID) REFERENCES up_person(ID) ON DELETE CASCADE,
    FOREIGN KEY (CHILD_ID) REFERENCES up_person(ID) ON DELETE CASCADE,
    PRIMARY KEY (PARENT_ID, CHILD_ID)
);

CREATE TABLE up_publication(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	USER_ID INT NOT NULL,
	MESSAGE TEXT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES up_user(ID)
);


CREATE TABLE up_comment(
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PARENT_ID INT DEFAULT NULL,
	PUBLICATION_ID INT NOT NULL,
	USER_ID INT NOT NULL,
	COMMENT TEXT NOT NULL,
	FOREIGN KEY (USER_ID) REFERENCES up_user(ID),
	FOREIGN KEY (PUBLICATION_ID) REFERENCES up_publication(ID)
);

CREATE TABLE up_comment_parent(
	PARENT_ID INT NOT NULL,
	CHILD_ID INT NOT NULL,
	FOREIGN KEY (PARENT_ID) REFERENCES up_comment(ID) ON DELETE CASCADE,
	FOREIGN KEY (CHILD_ID) REFERENCES up_comment(ID) ON DELETE CASCADE,
	PRIMARY KEY (PARENT_ID, CHILD_ID)
);

CREATE TABLE up_image(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    PATH VARCHAR(255) NOT NULL,
    PERSON_ID INT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES up_person(ID)
);

